{% set name = "hmsclient" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 908bdf1e082865d2b8a87a25290f8bd16b3bf4e71c028762231a9cfa49814286

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - click
    - python >={{ python_min }}
    - thrift

test:
  requires:
    - python {{ python_min }}
  imports:
    - hmsclient
    - hmsclient.genthrift
    - hmsclient.genthrift.fb303
    - hmsclient.genthrift.hive_metastore

about:
  home: https://github.com/gglanzani/hmsclient
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A package interact with the Hive metastore via the Thrift protocol
  doc_url: https://github.com/gglanzani/hmsclient
  dev_url: https://github.com/gglanzani/hmsclient

extra:
  recipe-maintainers:
    - xylar
